### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by rameezrehman83** [wuyang0329/unet#13]
Hi,
It gives me this error . 
Traceback (most recent call last):
  File "<encoding error>", line 48, in <module>
  File "C:\Users\Rameez\py32\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Rameez\py32\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Rameez\py32\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\Rameez\py32\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\Rameez\py32\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Rameez\py32\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\Rameez\AppData\Local\Programs\Python\Python35\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\Rameez\AppData\Local\Programs\Python\Python35\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Rameez\py32\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "G:\Experiments\Lab exp data\新建文件夹 (2)\unet-master\unet-master\data.py", line 108, in trainGenerator
    for (img, label) in train_generator:
  File "C:\Users\Rameez\py32\lib\site-packages\keras_preprocessing\image\iterator.py", line 100, in __next__
    return self.next(*args, **kwargs)
  File "C:\Users\Rameez\py32\lib\site-packages\keras_preprocessing\image\iterator.py", line 109, in next
    index_array = next(self.index_generator)
  File "C:\Users\Rameez\py32\lib\site-packages\keras_preprocessing\image\iterator.py", line 85, in _flow_index
    current_index = (self.batch_index * self.batch_size) % self.n
ZeroDivisionError: integer division or modulo by zero

**Comment by rameezrehman83** [comment]
It is solved. There was a problem in adding location of data. Thanks

**Comment by lyc1995452-star** [comment]
> It is solved. There was a problem in adding location of data. Thanks

How did you solve it？
