### ISSUE TITLE
KeyError: Train

### ISSUE THREAD

**Issue by hcao720** [wuyang0329/unet#20]
我就打中文了哦
感谢分享
请问这个报错是什么问题啊？
Traceback (most recent call last):
  File "/Users/hcao/Desktop/ing/ImageProcessing/Algorithm/unet-wuyang/train.py", line 48, in <module>
    callbacks=[model_checkpoint,tb_cb])
  File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/Users/hcao/.local/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/Users/hcao/Desktop/ing/ImageProcessing/Algorithm/unet-wuyang/data.py", line 96, in trainGenerator
    seed=seed)
  File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/preprocessing/image.py", line 572, in flow_from_directory
    interpolation=interpolation)
  File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/preprocessing/image.py", line 1213, in __init__
    classes, filenames = res.get()
  File "/Users/hcao/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/Users/hcao/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/preprocessing/image.py", line 1070, in _list_valid_filenames_in_directory
    classes.append(class_indices[dirname])
KeyError: 'train'

**Comment by wuyang0329** [comment]
检查一下你的训练集的路径是不是填错了

**Comment by hcao720** [comment]
是的，我自作聪明了
谢谢大佬！

**Comment by hcao720** [comment]
我想再问您一下
camvid的color_dict是如何构造的啊？我用我自己的数据集已经把label的形式调整的和camvid一致了，但是依然全黑，别的能想到的办法都试过了，感觉可能是color_dict的问题了

**Comment by lyc1995452-star** [comment]
> 是的，我自作聪明了
> 谢谢大佬！



> 我就打中文了哦
> 感谢分享
> 请问这个报错是什么问题啊？
> Traceback (most recent call last):
> File "/Users/hcao/Desktop/ing/ImageProcessing/Algorithm/unet-wuyang/train.py", line 48, in
> callbacks=[model_checkpoint,tb_cb])
> File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
> return func(*args, **kwargs)
> File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 2192, in fit_generator
> generator_output = next(output_generator)
> File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 793, in get
> six.reraise(value.**class**, value, value.**traceback**)
> File "/Users/hcao/.local/lib/python3.7/site-packages/six.py", line 693, in reraise
> raise value
> File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
> generator_output = next(self._generator)
> File "/Users/hcao/Desktop/ing/ImageProcessing/Algorithm/unet-wuyang/data.py", line 96, in trainGenerator
> seed=seed)
> File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/preprocessing/image.py", line 572, in flow_from_directory
> interpolation=interpolation)
> File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/preprocessing/image.py", line 1213, in **init**
> classes, filenames = res.get()
> File "/Users/hcao/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
> raise self._value
> File "/Users/hcao/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "/Users/hcao/anaconda3/lib/python3.7/site-packages/keras/preprocessing/image.py", line 1070, in _list_valid_filenames_in_directory
> classes.append(class_indices[dirname])
> KeyError: 'train'

你好，我也是这个错误，我数据集是按照这个格式来的啊，能指导一下吗？

**Comment by hcao720** [comment]
@lyc1995452-star 我后来用了另一个
https://github.com/divamgupta/image-segmentation-keras
你康康

**Comment by lyc1995452-star** [comment]
嗯，你这个复现完了吗？精度如何，可以加个好友交流一下吗？

**Comment by lyc1995452-star** [comment]
> @lyc1995452-star 我后来用了另一个
> https://github.com/divamgupta/image-segmentation-keras
> 你康康
    assert input_height % 32 == 0
AssertionError  你在复现遇到过这个问题吗？

**Comment by hcao720** [comment]
@lyc1995452-star 我很菜。。。你的微信号是啥我加你

**Comment by lyc1995452-star** [comment]
CUIT14-07
