### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by 960725** [wuyang0329/unet#3]

**Comment by 960725** [comment]
how to start

**Comment by wuyang0329** [comment]
you can put your train and test data into the data folder, and run the train.py to train your own model， then you can run the test.py  to test your model.

**Comment by 960725** [comment]
> you can put your train and test data into the data folder, and run the train.py to train your own model， then you can run the test.py  to test your model.
我需要先运行这个程度嘛，data_Pretreatment.py

**Comment by 960725** [comment]
我需要先运行这个程序嘛，data_Pretreatment.py

**Comment by wuyang0329** [comment]
> 我需要先运行这个程序嘛，data_Pretreatment.py

可以不用，直接将训练数据按照我的代码目录结构放好，然后把train.py中的路径修改成你自己的就可以了。

**Comment by wuyang0329** [comment]
> 我需要先运行这个程序嘛，data_Pretreatment.py

可以不用，直接将训练数据按照我的代码目录结构放好，然后把train.py中的路径修改成你自己的就可以了。

**Comment by 960725** [comment]
我使用的是您的数据 报了这个错误。应该怎么解决呢。谢谢

**Comment by wuyang0329** [comment]
> 我使用的是您的数据 报了这个错误。应该怎么解决呢。谢谢

Epoch 1/20
Found 0 images belonging to 1 classes.
Found 0 images belonging to 1 classes.

你的图片没有被读到，检查一下是不是路径错了

**Comment by 960725** [comment]
大哥 你可以加我qq嘛 我真的不知道哪里除了问题，路径我检查了几遍了 741032241@qq.com 谢谢你。

**Comment by manvirvirk** [comment]
> 您好，我报了这个错误。
> 
> Epoch 1/20
> Found 0 images belonging to 1 classes.
> Found 0 images belonging to 1 classes.
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "C:\Users\lds\Anaconda2\envs\py2\lib\threading.py", line 916, in _bootstrap_inner
> self.run()
> File "C:\Users\lds\Anaconda2\envs\py2\lib\threading.py", line 864, in run
> self._target(*self._args, **self._kwargs)
> File "C:\Users\lds\Anaconda2\envs\py2\lib\site-packages\keras\utils\data_utils.py", line 630, in data_generator_task
> generator_output = next(self._generator)
> File "G:\3\unet-master\data.py", line 100, in trainGenerator
> for (img, label) in train_generator:
> File "C:\Users\lds\Anaconda2\envs\py2\lib\site-packages\keras\preprocessing\image.py", line 794, in **next**
> return self.next(*args, **kwargs)
> File "C:\Users\lds\Anaconda2\envs\py2\lib\site-packages\keras\preprocessing\image.py", line 1132, in next
> index_array = next(self.index_generator)
> File "C:\Users\lds\Anaconda2\envs\py2\lib\site-packages\keras\preprocessing\image.py", line 779, in _flow_index
> current_index = (self.batch_index * self.batch_size) % self.n
> ZeroDivisionError: integer division or modulo by zero
> 
> Traceback (most recent call last):
> File "train.py", line 38, in
> model.fit_generator(train_data,steps_per_epoch=300,epochs=20,callbacks=[model_checkpoint])
> File "C:\Users\lds\Anaconda2\envs\py2\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
> return func(*args, **kwargs)
> File "C:\Users\lds\Anaconda2\envs\py2\lib\site-packages\keras\engine\training.py", line 2065, in fit_generator
> generator_output = next(output_generator)
> StopIteration

i m having same problem. Were you able to solve?
