### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by manvirvirk** [wuyang0329/unet#30]
whole traceback:
Instructions for updating:
Use tf.cast instead.
Found 0 images belonging to 1 classes.
Found 0 images belonging to 1 classes.
Found 0 images belonging to 1 classes.
Found 0 images belonging to 1 classes.
Epoch 1/30
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    callbacks=[model_checkpoint,tb_cb])
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\keras\engine\training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\keras\utils\data_utils.py", line 742, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\keras\utils\data_utils.py", line 711, in get
    inputs = future.get(timeout=30)
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\keras\utils\data_utils.py", line 650, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "D:\unet-master\data.py", line 109, in trainGenerator
    img, label = self.adjustData(img, label)
  File "D:\unet-master\data.py", line 71, in adjustData
    elif (np.max(img) > 1):
  File "<__array_function__ internals>", line 6, in amax
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\numpy\core\fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\numpy\core\fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by husheng876** [comment]
it may be caused by the error path of file

**Comment by tabarkarajab** [comment]
im getting the same issue after giving the correct paths for this
