### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by AliMedVisionTech** [wuyang0329/unet#31]
First of all thanks for your outstanding work. I am trying to run test.py file.... and getting this error. please give me some suggestions to get ride of this error.

Traceback (most recent call last):
  File "test.py", line 41, in <module>
    x,img_size = image_normalized(image_path)
  File "test.py", line 18, in image_normalized
    img_shape = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

............................................
here is my test.py file details.

from model_v2 import *
from data import *
import numpy as np
import cv2
import os
import warnings
import sys
warnings.filterwarnings("ignore")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

def image_normalized(file_path):
    '''
    tif，size:512*512，gr/ay
    :param dir_path: path to your images directory
    :return:
    '''
    img = cv2.imread(file_path)
    img_shape = img.shape
    image_size = (img_shape[1],img_shape[0])
    img_standard = cv2.resize(img, (512, 512), interpolation=cv2.INTER_CUBIC)
    img_new = img_standard
    img_new = np.asarray([img_new / 255.])
    return img_new,image_size

if __name__ == '__main__':

    #path to images which aring wating for predicting
    test_path = "/home/cuilei/unet-master/data/road/test"

    # save the predict images
    save_path = "/home/cuilei/unet-master/data/road/test/predict"

    dp = data_preprocess(test_path=test_path,save_path=save_path,flag_multi_class=True,num_classes=12)

    #load model
    model = load_model('/home/cuilei/unet-master/model/CamVid_model_v1.hdf5')

    for name in os.listdir(test_path):
        image_path = os.path.join(test_path,name)
        x,img_size = image_normalized(image_path)
        results = model.predict(x)
        dp.saveResult([results[0]],img_size,name.split('.')[0])

**Comment by HoraceXIaoyiBao** [comment]
Check your test folder if there are any files that is not a picture
